# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1

# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app

# Install dependencies and build
COPY package.json tsconfig.json ./
COPY src ./src
COPY bin ./bin
RUN npm install \
    && npm run build

# Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and dependencies
COPY --from=builder /app .

ENV NODE_ENV=production

# Default to stdio server
ENTRYPOINT ["node", "dist/index.js"]
